// Package wire holds the request and response types shared between the control
// plane and the agent.
//
// They live in their own package so that a change to a field is visibly a
// protocol change, reviewed as one, rather than an incidental edit to a handler
// or a client. Both sides compile against these types, so a breaking change
// fails the build instead of failing in production.
package wire

import (
	"encoding/json"
	"time"
)

// EnrollRequest is posted to the public enroll endpoint.
type EnrollRequest struct {
	// Credential is the plaintext enrollment code.
	Credential string `json:"credential"`

	// PublicKey is the host's raw static public key, base64 standard encoding.
	// The private half is generated on the host and never transmitted; there is
	// no field for it here and no column for it in the database.
	PublicKey string `json:"public_key"`

	// Curve is CURVE25519 or P256 and must match the network's.
	Curve string `json:"curve"`

	AgentVersion  string `json:"agent_version,omitempty"`
	NebulaVersion string `json:"nebula_version,omitempty"`

	// HostInfo is advisory metadata for the admin UI. It is never trusted for
	// any authorization decision.
	HostInfo map[string]string `json:"host_info,omitempty"`
}

// EnrollResponse carries everything a host needs to join.
type EnrollResponse struct {
	HostID   string `json:"host_id"`
	HostName string `json:"host_name"`

	// Certificate is this host's PEM certificate.
	Certificate string `json:"certificate"`
	// CABundle is every CA the host should trust, concatenated. It contains
	// more than the issuing CA during a rotation, which is what lets a CA be
	// published and converged before it starts signing.
	CABundle string `json:"ca_bundle"`
	// Config is the rendered 50-orbit.yml fragment.
	Config string `json:"config"`

	ConfigEpoch    int64 `json:"config_epoch"`
	BlocklistEpoch int64 `json:"blocklist_epoch"`

	// AgentEndpoints are overlay addresses, one per live control-plane replica.
	// From here on the host talks to the control plane over nebula and holds no
	// bearer credential.
	//
	// A list rather than a single value: an agent pinned to one replica loses
	// renewal and revocation when that replica goes away, which makes running a
	// second one redundancy for the database and nothing for the fleet.
	AgentEndpoints []string `json:"agent_endpoints,omitempty"`

	// RenewAfter is the midpoint of the certificate's lifetime. Renewing then
	// leaves the remaining half to recover from failure before expiry.
	RenewAfter time.Time `json:"renew_after"`
	NotAfter   time.Time `json:"not_after"`
}

// StateResponse is what the agent polls for.
type StateResponse struct {
	ConfigEpoch    int64 `json:"config_epoch"`
	BlocklistEpoch int64 `json:"blocklist_epoch"`

	// Config, CABundle, and Certificate are present only when the agent's
	// reported epoch is behind, so a steady-state poll is small.
	Config      string `json:"config,omitempty"`
	CABundle    string `json:"ca_bundle,omitempty"`
	Certificate string `json:"certificate,omitempty"`

	RenewAfter time.Time `json:"renew_after,omitempty"`
	NotAfter   time.Time `json:"not_after,omitempty"`
}

// ReportRequest is what an agent sends after successfully applying a config.
//
// Reported after applying, never after fetching. Reporting on fetch would make
// convergence measure download success and hide the case where a config was
// received but never took effect, which is exactly the failure a CA rotation
// must not advance past.
type ReportRequest struct {
	ConfigEpoch    int64  `json:"config_epoch"`
	BlocklistEpoch int64  `json:"blocklist_epoch"`
	NebulaVersion  string `json:"nebula_version,omitempty"`
	AgentVersion   string `json:"agent_version,omitempty"`
}

// RenewRequest asks for a fresh certificate. A new keypair is generated by
// default, so this carries a new public key.
type RenewRequest struct {
	PublicKey string `json:"public_key"`
	Curve     string `json:"curve"`
}

// RecoveryChallengeResponse is the server's half of the proof-of-possession
// exchange for a host whose certificate expired while it was offline.
type RecoveryChallengeResponse struct {
	Nonce           string    `json:"nonce"`
	ServerPublicKey string    `json:"server_public_key"`
	Curve           string    `json:"curve"`
	ExpiresAt       time.Time `json:"expires_at"`
}

// RecoverRequest redeems a challenge.
//
// The host proves possession of the private key from its last certificate by
// deriving the same shared secret the server can, and MACs the NEW public key
// with it. Binding the new key is what makes a captured proof useless to
// anyone else: it cannot be replayed to obtain a certificate for a key the
// attacker controls.
type RecoverRequest struct {
	HostID string `json:"host_id"`
	Nonce  string `json:"nonce"`
	// PublicKey is the new host key, generated locally as at enrollment.
	PublicKey string `json:"public_key"`
	Curve     string `json:"curve"`
	Proof     string `json:"proof"`
}

// CreateHostRequest is the admin API's host creation payload.
type CreateHostRequest struct {
	NetworkID    string   `json:"network_id"`
	Name         string   `json:"name"`
	OverlayAddr  string   `json:"overlay_addr"`
	RoleID       string   `json:"role_id,omitempty"`
	Tags         []string `json:"tags,omitempty"`
	IsLighthouse bool     `json:"is_lighthouse,omitempty"`
	IsRelay      bool     `json:"is_relay,omitempty"`
	StaticAddrs  []string `json:"static_addrs,omitempty"`
}

// UpdateHostRequest changes a host's roles and metadata.
//
// Pointer fields so "not supplied" is distinguishable from "set to false" or
// "set to empty". A PATCH that cannot express "leave this alone" forces callers
// to read-modify-write, which races.
type UpdateHostRequest struct {
	RoleID       *string   `json:"role_id,omitempty"`
	Tags         *[]string `json:"tags,omitempty"`
	IsLighthouse *bool     `json:"is_lighthouse,omitempty"`
	IsRelay      *bool     `json:"is_relay,omitempty"`
	StaticAddrs  *[]string `json:"static_addrs,omitempty"`
}

type HostResponse struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	NetworkID    string   `json:"network_id"`
	OverlayAddrs []string `json:"overlay_addrs"`
	State        string   `json:"state"`
	Tags         []string `json:"tags,omitempty"`
	IsLighthouse bool     `json:"is_lighthouse"`
	IsRelay      bool     `json:"is_relay"`

	AppliedConfigEpoch    int64      `json:"applied_config_epoch"`
	AppliedBlocklistEpoch int64      `json:"applied_blocklist_epoch"`
	LastSeenAt            *time.Time `json:"last_seen_at,omitempty"`
}

// EnrollmentCodeResponse returns a freshly minted code. The plaintext appears
// here and nowhere else, ever.
type EnrollmentCodeResponse struct {
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expires_at"`
	EnrollURL string    `json:"enroll_url"`
}

// BlockResponse reports the epoch a block landed in, so an operator (or a test)
// can watch convergence toward it.
type BlockResponse struct {
	BlocklistEpoch int64 `json:"blocklist_epoch"`
}

// ConvergenceResponse backs the rotation gate and the revocation SLO.
type ConvergenceResponse struct {
	ConfigEpoch    int64 `json:"config_epoch"`
	BlocklistEpoch int64 `json:"blocklist_epoch"`
	HostsTotal     int   `json:"hosts_total"`
	ConfigApplied  int   `json:"config_applied"`
	BlockApplied   int   `json:"blocklist_applied"`

	Lagging []LaggingHost `json:"lagging,omitempty"`
}

type LaggingHost struct {
	HostID                string     `json:"host_id"`
	Name                  string     `json:"name"`
	AppliedConfigEpoch    int64      `json:"applied_config_epoch"`
	AppliedBlocklistEpoch int64      `json:"applied_blocklist_epoch"`
	LastSeenAt            *time.Time `json:"last_seen_at,omitempty"`
}

// Error is the uniform error body. Message is safe to show a user; it never
// distinguishes "does not exist" from "you may not see it", because that
// distinction is exactly what a prober is looking for.
type Error struct {
	Error string `json:"error"`
}

// --- Admin: networks, roles, CAs, tokens, audit ---

type CreateNetworkRequest struct {
	Name string `json:"name"`
	// CIDRs are the overlay prefixes. Two networks may overlap: they are
	// separate meshes and never exchange traffic.
	CIDRs []string `json:"cidrs"`
	// CertTTL is the host certificate lifetime. This is the revocation SLA for
	// a partitioned host, not merely a rotation cadence, so the API states it
	// in those terms.
	CertTTL     string `json:"cert_ttl,omitempty"`
	Curve       string `json:"curve,omitempty"`
	CertVersion int    `json:"cert_version,omitempty"`
}

type NetworkResponse struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	CIDRs       []string `json:"cidrs"`
	Curve       string   `json:"curve"`
	CertVersion int      `json:"cert_version"`
	CertTTL     string   `json:"cert_ttl"`

	ConfigEpoch    int64 `json:"config_epoch"`
	BlocklistEpoch int64 `json:"blocklist_epoch"`
}

type CreateRoleRequest struct {
	NetworkID string   `json:"network_id"`
	Name      string   `json:"name"`
	Groups    []string `json:"groups,omitempty"`
	// Firewall is validated strictly before storage: nebula silently ignores
	// keys it does not recognise, so a typo would otherwise become a rule with
	// a different meaning than its author wrote.
	Firewall json.RawMessage `json:"firewall,omitempty"`
}

type RoleResponse struct {
	ID        string          `json:"id"`
	NetworkID string          `json:"network_id"`
	Name      string          `json:"name"`
	Groups    []string        `json:"groups,omitempty"`
	Firewall  json.RawMessage `json:"firewall,omitempty"`
}

type CreateCARequest struct {
	NetworkID string `json:"network_id"`
	Name      string `json:"name"`
	// Days is the CA lifetime. Host certificates cannot outlive it, so a short
	// CA forces a rotation cadence.
	Days int `json:"days,omitempty"`
	// Networks and Groups bound what subordinate certificates may claim. Empty
	// means unconstrained, which the API refuses: nebula has no intermediate
	// CAs, so this is the only blast-radius control there is.
	Networks []string `json:"networks,omitempty"`
	Groups   []string `json:"groups,omitempty"`
	// SignerRef locates the signing key: awskms://…, pkcs11://…, file://…
	SignerRef string `json:"signer_ref"`
}

// ActivateCARequest promotes a CA to signing.
//
// Activation is refused while hosts are still behind, because promoting past
// them partitions them off the mesh: they do not yet trust the new CA and their
// next renewal will be signed by it.
type ActivateCARequest struct {
	// AcknowledgeCutoff overrides that refusal.
	//
	// A typed field rather than a query flag, deliberately. This is the
	// emergency path after a signing-key compromise, where cutting off
	// unconverged hosts is the lesser harm — but it should be impossible to
	// take by accident, and it is audited as a distinct action.
	AcknowledgeCutoff bool `json:"acknowledge_cutoff,omitempty"`
}

type CAResponse struct {
	ID          string `json:"id"`
	NetworkID   string `json:"network_id"`
	Name        string `json:"name"`
	Fingerprint string `json:"fingerprint"`
	State       string `json:"state"`
	NotBefore   string `json:"not_before"`
	NotAfter    string `json:"not_after"`
	// CertPEM is what operators add to a trust bundle during rotation.
	CertPEM string `json:"cert_pem,omitempty"`

	// ActiveCertificates is how many live certificates this CA signed. A
	// retiring CA can be retired once this reaches zero.
	ActiveCertificates int `json:"active_certificates"`
}

type CreateTokenRequest struct {
	Name   string   `json:"name"`
	Scopes []string `json:"scopes"`
	// ExpiresInDays bounds the token. Zero means no expiry, which the API
	// permits but reports back so it is a visible choice.
	ExpiresInDays int `json:"expires_in_days,omitempty"`
}

type TokenResponse struct {
	ID string `json:"id"`
	// Token is the plaintext, returned exactly once and never stored.
	Token     string   `json:"token,omitempty"`
	Name      string   `json:"name"`
	Scopes    []string `json:"scopes"`
	ExpiresAt string   `json:"expires_at,omitempty"`
	CreatedAt string   `json:"created_at,omitempty"`
	// LastUsedAt is what makes a listing worth having: after a leak the
	// question is whether the token was used, and when.
	LastUsedAt string `json:"last_used_at,omitempty"`
	// RevokedAt is set on revoked tokens, which stay listed rather than
	// disappearing. A row that vanishes cannot answer "was it used after we
	// revoked it".
	RevokedAt string `json:"revoked_at,omitempty"`
}

// WhoAmIResponse describes the calling credential to itself.
//
// It never contains the token. The point is to answer "which credential am I
// holding, and is it still good" — for a break-glass check, and for the more
// common case of an operator with three tokens in three shells.
type WhoAmIResponse struct {
	// Kind is "token" today, "user" for an OIDC subject.
	Kind string `json:"kind"`
	// ID is the token uuid, or an issuer-qualified subject.
	ID       string   `json:"id"`
	Name     string   `json:"name,omitempty"`
	Scopes   []string `json:"scopes"`
	Unscoped bool     `json:"unscoped"`
	// ExpiresAt is empty when the credential does not expire.
	ExpiresAt string `json:"expires_at,omitempty"`
	// ExpiresInDays is negative for an already-expired credential, which cannot
	// authenticate — so seeing it here means a clock disagreement worth knowing
	// about.
	ExpiresInDays *int `json:"expires_in_days,omitempty"`
}

type AuditRecordResponse struct {
	ID        int64     `json:"id"`
	At        time.Time `json:"at"`
	ActorType string    `json:"actor_type"`
	ActorID   string    `json:"actor_id,omitempty"`
	// ActorDisplay is the actor's name as it was at the time — a token name, or
	// an email once OIDC subjects can authenticate. Present so a reader does
	// not have to resolve actor_id against a table the actor may have been
	// deleted from.
	ActorDisplay string          `json:"actor_display,omitempty"`
	Action       string          `json:"action"`
	TargetType   string          `json:"target_type,omitempty"`
	TargetID     string          `json:"target_id,omitempty"`
	Meta         json.RawMessage `json:"meta,omitempty"`
	SourceIP     string          `json:"source_ip,omitempty"`
}
