package agent

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestResolvConfRoundTrip is the property that matters on the weaker of the two Linux
// mechanisms: whatever was in the file comes back, byte for byte, and the machine that
// had working DNS before uninstall has working DNS after.
func TestResolvConfRoundTrip(t *testing.T) {
	dir := t.TempDir()
	resolvPath = filepath.Join(dir, "resolv.conf")
	t.Cleanup(func() { resolvPath = "/etc/resolv.conf" })

	original := "nameserver 192.168.1.1\nnameserver 1.1.1.1\nsearch lan\noptions edns0\n"
	if err := os.WriteFile(resolvPath, []byte(original), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := writeResolvConf("lab.internal", "10.42.0.5:53"); err != nil {
		t.Fatal(err)
	}
	got := read(t, resolvPath)
	if !strings.Contains(got, "nameserver 10.42.0.5") {
		t.Errorf("resolver not installed:\n%s", got)
	}
	if !strings.Contains(got, "search lab.internal") {
		t.Errorf("search domain not installed:\n%s", got)
	}

	// Applying twice must not eat the original, which is what happens when the
	// second run preserves the first run's output instead of what it displaced.
	if err := writeResolvConf("lab.internal", "10.42.0.5:53"); err != nil {
		t.Fatal(err)
	}

	if err := restoreResolvConf(); err != nil {
		t.Fatal(err)
	}
	if got := read(t, resolvPath); got != original {
		t.Errorf("restore did not put the file back.\n got: %q\nwant: %q", got, original)
	}
}

// TestRestoreLeavesForeignFilesAlone: something else took the file over while we were
// running. Restoring on top would clobber whatever actually knows what the resolvers
// should be by now.
func TestRestoreLeavesForeignFilesAlone(t *testing.T) {
	dir := t.TempDir()
	resolvPath = filepath.Join(dir, "resolv.conf")
	t.Cleanup(func() { resolvPath = "/etc/resolv.conf" })

	foreign := "# Generated by NetworkManager\nnameserver 10.0.0.1\n"
	if err := os.WriteFile(resolvPath, []byte(foreign), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := restoreResolvConf(); err != nil {
		t.Fatal(err)
	}
	if got := read(t, resolvPath); got != foreign {
		t.Errorf("a file Orbit did not write was modified:\n%s", got)
	}
}

func read(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}
