package agent

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

// Service files for the agent, generated rather than copied.
//
// A unit file in a docs directory is a unit file that drifts: the flags change,
// the example does not, and an operator pastes something that has not worked
// since two releases ago. This renders from the values the agent already
// resolved — the directory it owns, the slug, the binary's own path — so there
// is nothing to keep in step.

// ServicePlan is what installing the agent as a service will do, computed
// before anything is written so it can be shown and refused.
type ServicePlan struct {
	// Manager is "systemd" or "launchd".
	Manager string
	// Path is where the unit or plist goes.
	Path string
	// Name is what the service manager calls it.
	Name string
	// Contents is the rendered file.
	Contents string
	// Start, Restart and Status are the commands that bring it up, cycle it and
	// report on it, shown to the operator so the next step is never a guess.
	//
	// RESTART EXISTS BECAUSE THE GUIDANCE KEPT SAYING systemctl. The plan has
	// always known the platform — it renders a plist on darwin and a unit on
	// Linux — while everything an operator READ assumed systemd, so a Mac was
	// told to run a command it does not have. The machinery being right does not
	// help if the sentence next to it is wrong.
	Start   []string
	Restart []string
	Status  []string
}

// PlanService renders the service definition for this platform.
//
// slug names the instance so a host on two networks runs two services over two
// directories with nothing shared — the same %i that has always identified a
// network here.
func PlanService(root, binary, verifyURL string) (ServicePlan, error) {
	if binary == "" {
		return ServicePlan{}, fmt.Errorf("no path to the orbit binary")
	}

	// No -dir. The service runs EVERY network joined under the root, and the
	// set of them is the set of directories — so adding a network is enrolling
	// into a new one, and the service definition never changes.
	//
	// Naming a directory here is what made the templated version wrong: it
	// pinned one unit to one network while pretending to serve all of them.
	args := []string{"agent", "run"}
	if root != "" && root != DefaultRoot {
		args = append(args, "-root", root)
	}
	if verifyURL != "" {
		args = append(args, "-verify-url", verifyURL)
	}

	switch runtime.GOOS {
	case "linux":
		return systemdPlan(binary, args, root), nil
	case "darwin":
		return launchdPlan(binary, args), nil
	default:
		return ServicePlan{}, fmt.Errorf(
			"no service integration for %s; run `orbit agent run` under whatever "+
				"supervises long-running processes here", runtime.GOOS)
	}
}

func systemdPlan(binary string, args []string, root string) ServicePlan {
	// ONE unit, not one per network.
	//
	// The agent serves every joined network from a single process, so there is
	// nothing per-network in the unit and nothing for a second install to
	// rewrite. That is worth stating because the templated version of this was
	// wrong in a way that looked fine: a template is one shared file, and baking
	// a directory into it meant installing a second network silently repointed
	// the first network's instance at the second's directory — two healthy-
	// looking units serving one network.
	//
	// Adding a network is now enrolling into a new directory; the running agent
	// picks it up on restart, and this file does not change.
	const name = "orbit-agent"
	return ServicePlan{
		Manager: "systemd",
		Name:    name,
		Path:    "/etc/systemd/system/" + name + ".service",
		Start:   []string{"systemctl", "daemon-reload", "&&", "systemctl", "enable", "--now", name},
		Restart: []string{"systemctl", "restart", name},
		Status:  []string{"systemctl", "status", name},
		Contents: `# Orbit agent. One process, every network this host has joined.
#
# Generated by ` + "`orbit agent install`" + `. Regenerating it is the supported way
# to change it — hand edits are lost on the next install.
#
# There is no separate nebula unit and no per-network instance. The agent runs a
# nebula inside itself for each joined network, so this is the only thing to
# enable, and stopping it stops every overlay on this host.

[Unit]
Description=Orbit agent
After=network-online.target
Wants=network-online.target

[Service]
Type=exec
ExecStart=` + binary + ` ` + strings.Join(args, " ") + `

Restart=always
RestartSec=5s

# Root, and specifically for the tun devices. The agent creates one interface
# per network itself rather than asking a separate nebula to; CAP_NET_ADMIN is
# the part that matters, and the rest is given away below.
AmbientCapabilities=CAP_NET_ADMIN
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
RestrictNamespaces=yes
LockPersonality=yes
SystemCallArchitectures=native

# Every network's directory lives under this root, so one path covers them all
# — and state stays out of /etc, where an image-based system (bootc, OSTree)
# would reconcile it away on upgrade.
ReadWritePaths=` + rootOrDefault(root) + `

[Install]
WantedBy=multi-user.target
`,
	}
}

func launchdPlan(binary string, args []string) ServicePlan {
	const label = "com.griffithind.orbit.agent"
	var argXML strings.Builder
	argXML.WriteString("\t\t<string>" + binary + "</string>\n")
	for _, a := range args {
		argXML.WriteString("\t\t<string>" + a + "</string>\n")
	}

	return ServicePlan{
		Manager: "launchd",
		Name:    label,
		Path:    "/Library/LaunchDaemons/" + label + ".plist",
		Start:   []string{"launchctl", "bootstrap", "system", "/Library/LaunchDaemons/" + label + ".plist"},
		// kickstart -k rather than unload/load: it restarts a running job and
		// starts a stopped one, which is the behaviour `systemctl restart` has
		// and the reason an operator reaches for it.
		Restart: []string{"launchctl", "kickstart", "-k", "system/" + label},
		Status:  []string{"launchctl", "print", "system/" + label},
		Contents: `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!--
  Orbit agent. Generated by ` + "`orbit agent install`" + `.

  A LaunchDaemon, not a LaunchAgent: it runs as root at boot with no user logged
  in, because it creates a utun device. A LaunchAgent would start at login and
  stop at logout, which would take the mesh down when somebody signs out.
-->
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>` + label + `</string>
	<key>ProgramArguments</key>
	<array>
` + argXML.String() + `	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>KeepAlive</key>
	<true/>
	<key>StandardErrorPath</key>
	<string>/var/log/orbit-agent.log</string>
	<key>StandardOutPath</key>
	<string>/var/log/orbit-agent.log</string>
</dict>
</plist>
`,
	}
}

func rootOrDefault(root string) string {
	if root == "" {
		return DefaultRoot
	}
	return root
}

// Write puts the file in place.
//
// 0644, because a service manager reads it as root and it holds no secret: the
// certificate, the key, and the enrollment state are all under the agent's
// directory, and the unit only names paths.
func (p ServicePlan) Write() error {
	if err := os.MkdirAll(filepath.Dir(p.Path), 0o755); err != nil {
		return fmt.Errorf("create %s: %w", filepath.Dir(p.Path), err)
	}
	if err := os.WriteFile(p.Path, []byte(p.Contents), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", p.Path, err)
	}
	return nil
}

// Enable starts the service and asks it to start at boot.
func (p ServicePlan) Enable() error {
	switch p.Manager {
	case "systemd":
		if out, err := exec.Command("systemctl", "daemon-reload").CombinedOutput(); err != nil {
			return fmt.Errorf("systemctl daemon-reload: %w: %s", err, strings.TrimSpace(string(out)))
		}
		out, err := exec.Command("systemctl", "enable", "--now", p.Name).CombinedOutput()
		if err != nil {
			return fmt.Errorf("systemctl enable --now %s: %w: %s", p.Name, err, strings.TrimSpace(string(out)))
		}
	case "launchd":
		// bootout first, ignoring failure: on a reinstall the label is already
		// loaded and bootstrap refuses, which would make the second install of
		// the same host fail for no reason an operator can act on.
		_ = exec.Command("launchctl", "bootout", "system/"+p.Name).Run()
		out, err := exec.Command("launchctl", "bootstrap", "system", p.Path).CombinedOutput()
		if err != nil {
			return fmt.Errorf("launchctl bootstrap: %w: %s", err, strings.TrimSpace(string(out)))
		}
	default:
		return fmt.Errorf("cannot enable a service under %q", p.Manager)
	}
	return nil
}

// Disable stops the service and takes it out of the boot sequence.
//
// Every step tolerates "it was not there": uninstalling a half-installed host
// is the common case, and an uninstall that refuses because one piece is
// already gone leaves an operator to finish it by hand.
func (p ServicePlan) Disable() error {
	switch p.Manager {
	case "systemd":
		_ = exec.Command("systemctl", "disable", "--now", p.Name).Run()
		_ = exec.Command("systemctl", "daemon-reload").Run()
	case "launchd":
		_ = exec.Command("launchctl", "bootout", "system/"+p.Name).Run()
	default:
		return fmt.Errorf("cannot disable a service under %q", p.Manager)
	}
	return nil
}

// RemoveUnit deletes the service definition.
//
// A TEMPLATE unit is shared by every network on this host, so removing it while
// another instance is enabled would disable that one too. Reports whether it
// actually removed anything so the caller can say which happened.
func (p ServicePlan) RemoveUnit(otherInstances bool) (removed bool, err error) {
	if otherInstances && strings.Contains(filepath.Base(p.Path), "@") {
		return false, nil
	}
	if err := os.Remove(p.Path); err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("remove %s: %w", p.Path, err)
	}
	return true, nil
}

// EnabledInstances lists the other networks whose services are installed on
// this host, by reading the directories rather than asking a service manager —
// the directory is what the agent owns, and it exists whether or not anything
// is currently enabled.
func EnabledInstances(root, except string) ([]string, error) {
	entries, err := os.ReadDir(root)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var out []string
	for _, e := range entries {
		if !e.IsDir() || e.Name() == except {
			continue
		}
		// A directory is only another network if it holds agent state; a
		// leftover empty directory is not something to keep a shared unit for.
		if _, err := os.Stat(filepath.Join(root, e.Name(), StateFileName)); err == nil {
			out = append(out, e.Name())
		}
	}
	return out, nil
}

// ServiceCommands returns the restart and status commands for this platform.
//
// For the places that need to TELL somebody what to run without installing
// anything — `orbit status` reporting a dead data plane, most of all. It reaches
// through PlanService so there is one source of truth: a platform whose commands
// change here changes everywhere they are printed.
func ServiceCommands() (restart, status string) {
	// A placeholder binary path: nothing is written, and only the manager's own
	// command names are read back out.
	plan, err := PlanService("", "orbit", "")
	if err != nil {
		// A platform with no service manager has nothing to suggest, and a
		// guess would be worse than silence.
		return "", ""
	}
	return strings.Join(plan.Restart, " "), strings.Join(plan.Status, " ")
}
