package agent

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

// Service files for the agent, generated rather than copied.
//
// A unit file in a docs directory is a unit file that drifts: the flags change,
// the example does not, and an operator pastes something that has not worked
// since two releases ago. This renders from the values the agent already
// resolved — the directory it owns, the slug, the binary's own path — so there
// is nothing to keep in step.

// ServicePlan is what installing the agent as a service will do, computed
// before anything is written so it can be shown and refused.
type ServicePlan struct {
	// Manager is "systemd" or "launchd".
	Manager string
	// Path is where the unit or plist goes.
	Path string
	// Name is what the service manager calls it.
	Name string
	// Contents is the rendered file.
	Contents string
	// Start and Status are the commands that bring it up and report on it,
	// shown to the operator so the next step is never a guess.
	Start  []string
	Status []string
}

// PlanService renders the service definition for this platform.
//
// slug names the instance so a host on two networks runs two services over two
// directories with nothing shared — the same %i that has always identified a
// network here.
func PlanService(slug, dir, binary string, verifyURL string) (ServicePlan, error) {
	if err := ValidateNetwork(slug); err != nil {
		return ServicePlan{}, err
	}
	if binary == "" {
		return ServicePlan{}, fmt.Errorf("no path to the orbit binary")
	}

	args := []string{"agent", "run", "-dir", dir}
	if verifyURL != "" {
		args = append(args, "-verify-url", verifyURL)
	}

	switch runtime.GOOS {
	case "linux":
		return systemdPlan(slug, dir, binary, args), nil
	case "darwin":
		return launchdPlan(slug, binary, args), nil
	default:
		return ServicePlan{}, fmt.Errorf(
			"no service integration for %s; run `orbit agent run -dir %s` under whatever "+
				"supervises long-running processes here", runtime.GOOS, dir)
	}
}

func systemdPlan(slug, dir, binary string, args []string) ServicePlan {
	name := "orbit-agent@" + slug
	return ServicePlan{
		Manager: "systemd",
		Name:    name,
		Path:    "/etc/systemd/system/orbit-agent@.service",
		Start:   []string{"systemctl", "daemon-reload", "&&", "systemctl", "enable", "--now", name},
		Status:  []string{"systemctl", "status", name},
		Contents: `# Orbit agent. One instance PER NETWORK; %i is the network slug.
#
# Generated by ` + "`orbit agent install`" + `. Regenerating it is the supported way
# to change it — hand edits are lost on the next install.
#
# There is no separate nebula unit. The agent runs nebula in-process, so this is
# the only thing to enable, and stopping it stops the data plane on this host.

[Unit]
Description=Orbit agent (%i)
After=network-online.target
Wants=network-online.target

[Service]
Type=exec
ExecStart=` + binary + ` ` + strings.Join(args, " ") + `

Restart=always
RestartSec=5s

# Root, and specifically for the tun device. The agent creates the interface
# itself now rather than asking a separate nebula to; CAP_NET_ADMIN is the part
# that matters, and the rest is given away below.
AmbientCapabilities=CAP_NET_ADMIN
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
RestrictNamespaces=yes
LockPersonality=yes
SystemCallArchitectures=native

# Everything this host's agent owns lives here rather than in /etc, so an
# image-based system (bootc, OSTree) does not reconcile runtime state away on
# upgrade.
ReadWritePaths=` + dir + `

[Install]
WantedBy=multi-user.target
`,
	}
}

func launchdPlan(slug, binary string, args []string) ServicePlan {
	label := "com.griffithind.orbit.agent." + slug
	var argXML strings.Builder
	argXML.WriteString("\t\t<string>" + binary + "</string>\n")
	for _, a := range args {
		argXML.WriteString("\t\t<string>" + a + "</string>\n")
	}

	return ServicePlan{
		Manager: "launchd",
		Name:    label,
		Path:    "/Library/LaunchDaemons/" + label + ".plist",
		Start:   []string{"launchctl", "bootstrap", "system", "/Library/LaunchDaemons/" + label + ".plist"},
		Status:  []string{"launchctl", "print", "system/" + label},
		Contents: `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!--
  Orbit agent. Generated by ` + "`orbit agent install`" + `.

  A LaunchDaemon, not a LaunchAgent: it runs as root at boot with no user logged
  in, because it creates a utun device. A LaunchAgent would start at login and
  stop at logout, which would take the mesh down when somebody signs out.
-->
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>` + label + `</string>
	<key>ProgramArguments</key>
	<array>
` + argXML.String() + `	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>KeepAlive</key>
	<true/>
	<key>StandardErrorPath</key>
	<string>/var/log/orbit-agent-` + slug + `.log</string>
	<key>StandardOutPath</key>
	<string>/var/log/orbit-agent-` + slug + `.log</string>
</dict>
</plist>
`,
	}
}

// Write puts the file in place.
//
// 0644, because a service manager reads it as root and it holds no secret: the
// certificate, the key, and the enrollment state are all under the agent's
// directory, and the unit only names paths.
func (p ServicePlan) Write() error {
	if err := os.MkdirAll(filepath.Dir(p.Path), 0o755); err != nil {
		return fmt.Errorf("create %s: %w", filepath.Dir(p.Path), err)
	}
	if err := os.WriteFile(p.Path, []byte(p.Contents), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", p.Path, err)
	}
	return nil
}

// Enable starts the service and asks it to start at boot.
func (p ServicePlan) Enable() error {
	switch p.Manager {
	case "systemd":
		if out, err := exec.Command("systemctl", "daemon-reload").CombinedOutput(); err != nil {
			return fmt.Errorf("systemctl daemon-reload: %w: %s", err, strings.TrimSpace(string(out)))
		}
		out, err := exec.Command("systemctl", "enable", "--now", p.Name).CombinedOutput()
		if err != nil {
			return fmt.Errorf("systemctl enable --now %s: %w: %s", p.Name, err, strings.TrimSpace(string(out)))
		}
	case "launchd":
		// bootout first, ignoring failure: on a reinstall the label is already
		// loaded and bootstrap refuses, which would make the second install of
		// the same host fail for no reason an operator can act on.
		_ = exec.Command("launchctl", "bootout", "system/"+p.Name).Run()
		out, err := exec.Command("launchctl", "bootstrap", "system", p.Path).CombinedOutput()
		if err != nil {
			return fmt.Errorf("launchctl bootstrap: %w: %s", err, strings.TrimSpace(string(out)))
		}
	default:
		return fmt.Errorf("cannot enable a service under %q", p.Manager)
	}
	return nil
}
