-- Orbit schema.
--
-- One deployment manages the networks of one organization.
--
-- A network is the unit of separation: its own CA, address space, hosts, and
-- epochs. Nothing crosses between them, and a certificate issued by one
-- network's CA does not verify against another's. Two networks may use the same
-- prefix — prod and staging both on 10.42.0.0/16 is common — which is why the
-- agent API resolves a host by (network, address) rather than by address alone.
--
-- Invariants that protect correctness live in the database, not in Go. A
-- control plane that mints identities cannot rely on application-layer checks
-- that a concurrent request can race.

CREATE SCHEMA IF NOT EXISTS orbit;

-- State values are text + CHECK rather than enums. Postgres enums cannot have a
-- value added and used in the same transaction, which makes migrations that
-- introduce a new state awkward; a CHECK constraint is a plain ALTER.

CREATE TABLE orbit.api_token (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name         text NOT NULL,
    -- SHA-256 of the presented token. Tokens are 256-bit and generated by us,
    -- so a fast hash is correct: there is nothing to brute force. Enrollment
    -- codes are different (see enrollment_credential).
    token_hash   bytea NOT NULL UNIQUE,
    scopes       text[] NOT NULL DEFAULT '{}',
    expires_at   timestamptz,
    last_used_at timestamptz,
    revoked_at   timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE orbit.network (
    id    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name  text NOT NULL UNIQUE,
    -- Overlay prefixes. Two networks may overlap: they are separate meshes and
    -- never exchange traffic.
    cidrs cidr[] NOT NULL,
    cert_version smallint NOT NULL DEFAULT 2 CHECK (cert_version IN (1, 2)),
    curve text NOT NULL DEFAULT 'CURVE25519' CHECK (curve IN ('CURVE25519', 'P256')),
    -- Certificate lifetime. This is the revocation SLA for a partitioned host
    -- (docs/revocation.md), not merely a rotation cadence.
    cert_ttl interval NOT NULL DEFAULT '24 hours' CHECK (cert_ttl > interval '0'),
    -- Monotonic. Bumped in the same transaction as the change that caused it,
    -- alongside a pg_notify. Agents report the epoch they applied, which is
    -- what makes convergence measurable.
    config_epoch    bigint NOT NULL DEFAULT 1,
    blocklist_epoch bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE orbit.ca (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    network_id  uuid NOT NULL REFERENCES orbit.network (id) ON DELETE CASCADE,
    name        text NOT NULL,
    fingerprint text NOT NULL,
    cert_pem    text NOT NULL,
    -- Opaque reference resolved by internal/ca into a Signer:
    --   awskms://<region>/<key-id>, pkcs11://..., file://<path>
    -- Never contains key material.
    signer_ref  text NOT NULL,
    curve       text NOT NULL CHECK (curve IN ('CURVE25519', 'P256')),
    not_before  timestamptz NOT NULL,
    not_after   timestamptz NOT NULL,
    state       text NOT NULL DEFAULT 'pending'
                CHECK (state IN ('pending', 'active', 'retiring', 'retired')),
    created_at  timestamptz NOT NULL DEFAULT now(),

    UNIQUE (network_id, fingerprint),
    CHECK (not_after > not_before)
);
-- Issuance must be unambiguous: exactly one CA can be signing at a time.
-- Rotation moves the old CA to 'retiring' in the same transaction that promotes
-- the new one, so this never blocks a valid rotation.
CREATE UNIQUE INDEX ca_one_active_per_network
    ON orbit.ca (network_id) WHERE state = 'active';

CREATE TABLE orbit.role (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    network_id uuid NOT NULL REFERENCES orbit.network (id) ON DELETE CASCADE,
    name       text NOT NULL,
    -- Must be a subset of the signing CA's groups or issuance fails; nebula
    -- enforces this (cert/ca_pool.go checkCAConstraints).
    groups     text[] NOT NULL DEFAULT '{}',
    -- Rendered into config.d/50-orbit.yml. Nebula APPENDS rules across config
    -- files rather than replacing them.
    firewall_rules jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),

    UNIQUE (network_id, name)
);

CREATE TABLE orbit.host (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    network_id uuid NOT NULL REFERENCES orbit.network (id) ON DELETE CASCADE,
    name       text NOT NULL,
    role_id    uuid REFERENCES orbit.role (id) ON DELETE SET NULL,
    tags       text[] NOT NULL DEFAULT '{}',
    is_lighthouse bool NOT NULL DEFAULT false,
    is_relay      bool NOT NULL DEFAULT false,
    -- Underlay "host:port" entries for lighthouses and relays.
    static_addrs  text[] NOT NULL DEFAULT '{}',
    state      text NOT NULL DEFAULT 'created'
               CHECK (state IN ('created', 'enrolled', 'active', 'suspended', 'deleted')),
    -- Reported by the agent AFTER a successful apply, not after a fetch.
    -- Reporting on fetch would hide the failure mode where config was
    -- downloaded but never took effect.
    applied_config_epoch    bigint NOT NULL DEFAULT 0,
    applied_blocklist_epoch bigint NOT NULL DEFAULT 0,
    last_seen_at   timestamptz,
    nebula_version text,
    agent_version  text,
    created_at     timestamptz NOT NULL DEFAULT now(),

    UNIQUE (network_id, name)
);
CREATE INDEX host_network_state_idx ON orbit.host (network_id, state);
CREATE INDEX host_convergence_idx
    ON orbit.host (network_id, applied_blocklist_epoch, applied_config_epoch);

-- Overlay addresses live in their own table so uniqueness within a network is
-- enforced by the database, and so the agent API's "resolve host by source
-- overlay address" is a primary key hit.
CREATE TABLE orbit.host_address (
    network_id uuid NOT NULL REFERENCES orbit.network (id) ON DELETE CASCADE,
    host_id    uuid NOT NULL REFERENCES orbit.host (id) ON DELETE CASCADE,
    addr       inet NOT NULL,

    PRIMARY KEY (network_id, addr)
);
CREATE INDEX host_address_host_idx ON orbit.host_address (host_id);

CREATE TABLE orbit.certificate (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    host_id     uuid NOT NULL REFERENCES orbit.host (id) ON DELETE CASCADE,
    ca_id       uuid NOT NULL REFERENCES orbit.ca (id),
    fingerprint text NOT NULL UNIQUE,
    pem         text NOT NULL,
    cert_version smallint NOT NULL CHECK (cert_version IN (1, 2)),
    not_before  timestamptz NOT NULL,
    not_after   timestamptz NOT NULL,
    state       text NOT NULL DEFAULT 'active'
                CHECK (state IN ('pending', 'active', 'superseded', 'revoked')),
    issued_at   timestamptz NOT NULL DEFAULT now(),

    CHECK (not_after > not_before)
);
-- Scoped by cert_version, not just host: nebula holds a v1 and a v2 certificate
-- simultaneously during a version migration, and both are legitimately active.
CREATE UNIQUE INDEX certificate_one_active_per_host_version
    ON orbit.certificate (host_id, cert_version) WHERE state = 'active';
CREATE INDEX certificate_renewal_idx
    ON orbit.certificate (not_after) WHERE state = 'active';

CREATE TABLE orbit.enrollment_credential (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    network_id uuid NOT NULL REFERENCES orbit.network (id) ON DELETE CASCADE,
    -- NULL for cloud_iid, where the host record is created on redemption
    -- because autoscaled instances do not exist when the rule is written.
    host_id    uuid REFERENCES orbit.host (id) ON DELETE CASCADE,
    method     text NOT NULL CHECK (method IN ('code', 'cloud_iid', 'attestation')),
    -- HMAC-SHA256(pepper, code). Keyed rather than plain so a database leak
    -- alone yields no usable codes, and deterministic so redemption is a single
    -- indexed lookup. See internal/enroll/credential.go for why a slow KDF is
    -- the wrong tool for a 192-bit random value.
    secret_hash bytea NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    used_at    timestamptz,
    used_from  inet,
    created_by text,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX enrollment_credential_expiry_idx
    ON orbit.enrollment_credential (expires_at) WHERE used_at IS NULL;

-- Enforces single-use for cloud instance identity documents. Uniqueness must be
-- a constraint rather than an application check: an attacker replaying an IID
-- races the check, but cannot race a unique index.
CREATE TABLE orbit.enrolled_instance (
    provider    text NOT NULL,
    instance_id text NOT NULL,
    network_id  uuid NOT NULL REFERENCES orbit.network (id) ON DELETE CASCADE,
    host_id     uuid NOT NULL REFERENCES orbit.host (id) ON DELETE CASCADE,
    enrolled_at timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (provider, instance_id)
);

CREATE TABLE orbit.blocklist_entry (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    network_id  uuid NOT NULL REFERENCES orbit.network (id) ON DELETE CASCADE,
    fingerprint text NOT NULL,
    reason      text,
    epoch       bigint NOT NULL,
    -- NotAfter of the revoked certificate. Once passed the entry can be pruned:
    -- nebula rejects an expired certificate before it consults the blocklist,
    -- so keeping the fingerprint costs bytes in every host's config and buys
    -- nothing. See docs/revocation.md.
    not_after   timestamptz NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),

    UNIQUE (network_id, fingerprint)
);
CREATE INDEX blocklist_entry_live_idx ON orbit.blocklist_entry (network_id, not_after);

-- Control-plane service discovery.
--
-- Agents need to reach *a* control plane, not a specific one. Each replica
-- registers the overlay address it serves on and refreshes it; stale rows are
-- pruned by the maintenance sweep, so a replica that dies stops being
-- advertised without anyone deregistering it.
CREATE TABLE orbit.control_plane (
    network_id uuid NOT NULL REFERENCES orbit.network (id) ON DELETE CASCADE,
    host_id    uuid NOT NULL REFERENCES orbit.host (id) ON DELETE CASCADE,
    addr       inet NOT NULL,
    agent_port int  NOT NULL CHECK (agent_port > 0 AND agent_port < 65536),
    last_seen_at timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (network_id, addr)
);
CREATE INDEX control_plane_liveness_idx ON orbit.control_plane (network_id, last_seen_at DESC);

CREATE TABLE orbit.audit_log (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    actor_type  text NOT NULL CHECK (actor_type IN ('user', 'token', 'agent', 'system')),
    actor_id    text,
    action      text NOT NULL,
    target_type text,
    target_id   text,
    meta        jsonb NOT NULL DEFAULT '{}'::jsonb,
    source_ip   inet,
    at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_log_at_idx ON orbit.audit_log (at DESC);
