-- An index for reading a host's certificate history.
--
-- 0001 indexes orbit.certificate three ways, and every one of them is partial
-- on state = 'active': the renewal sweep's (not_after), the per-host-and-version
-- uniqueness, and the per-CA usage count. Nothing indexes host_id on its own, so
-- every query that reads a host's certificates regardless of state — the new
-- listing, and LatestCertificate, which recovery depends on — is a sequential
-- scan of every certificate ever issued in the deployment.
--
-- That cost is not incidental. Certificate rows are never deleted except by host
-- cascade, so the table grows with (hosts × renewals) forever: a thousand hosts
-- renewing hourly add nearly nine million rows a year, and the two paths above
-- would walk all of them to answer a question about one host.
--
-- The column order is the listing's ORDER BY, so the index supplies the sort and
-- the keyset comparison (issued_at, id) < (…, …) can be driven directly rather
-- than sorted after the fact. It carries no WHERE clause, deliberately: a
-- history is about superseded and revoked rows as much as active ones, and a
-- partial index would leave exactly this query back on a sequential scan.
--
-- No GRANT accompanies this file: it creates no table, and an index inherits the
-- privileges of the table it is on.
CREATE INDEX IF NOT EXISTS certificate_host_issued_idx
    ON orbit.certificate (host_id, issued_at DESC, id DESC);
