-- When a role's groups last changed, so certificates issued before that can be
-- pulled forward instead of waiting out their own half-life.
--
-- Groups are embedded in the signed certificate, so editing them leaves every
-- host carrying the role presenting the old set until it renews. Renewal is
-- host-driven at the midpoint of each certificate's own lifetime, which on the
-- default 24h certificate means a median of ~6h and a tail past 12h. For an
-- access-control change that is not a delay, it is a period in which the policy
-- an operator has been told is live demonstrably is not.
--
-- The agent already accepts a server-supplied RenewAfter and will pull renewal
-- forward, spread across PullForwardSpread so a fleet does not stampede
-- (internal/agent/renew.go, RenewAtWithHint). What was missing was any reason
-- for the server to send one: enroll.Service.State emitted the certificate's
-- own midpoint unconditionally, which is exactly the value the agent is
-- documented to ignore because it restates what the agent already computes. The
-- mechanism was complete on one side and never triggered from the other.
--
-- This column is that reason. State compares a host's active certificate
-- against its role's groups_changed_at: issued before it, the certificate
-- asserts groups that no longer match the role, and renewal is pulled forward.
--
-- A timestamp rather than an epoch: it is compared against certificate.issued_at
-- and nothing else, and the config epoch already exists for the thing epochs are
-- for. NULL means the groups have never changed since the role was created,
-- which is the common case and costs no comparison.
--
-- Deliberately NOT reset once the fleet converges. A stale marker is harmless —
-- every certificate issued after it compares false — and a sweep that cleared it
-- would be one more thing that can run at the wrong moment.

ALTER TABLE orbit.role
    ADD COLUMN groups_changed_at timestamptz;
