-- Hardware-backed keys are gone, so the column that recorded them is too.
--
-- WHY IT IS GOING.
--
-- device.key_backing recorded 'file' or 'token' — where a machine claimed to
-- hold its private key. Orbit no longer has a token path: no PKCS#11, no TPM,
-- no Secure Enclave, in either the device identity key or the mesh key. Every
-- device is 'file', which makes this a column with one value.
--
-- The reasoning for dropping the feature, not just the column: hardware backing
-- defeats OFFLINE attacks — a stolen disk, a backup, a decommissioned SSD — and
-- does nothing against an attacker with code execution on a running machine,
-- who simply asks the chip. That is a real but narrow category, and it cost a
-- cgo build variant, a second release artifact, and tpm2-pkcs11 on every
-- managed host. Tailscale and ZeroTier do not do it either. See git history if
-- it is ever wanted back; the removal was deliberate, not an oversight.
--
-- The column was also never more than a CLAIM. It was self-reported by the
-- agent and displayed as "(claimed)", because nothing attested it — a machine
-- whose agent had been replaced could report anything. A field that cannot be
-- trusted and now cannot vary is worth less than the line it occupies.

ALTER TABLE orbit.device DROP COLUMN key_backing;
