-- When a membership's routes last changed, so the certificate can catch up.
--
-- THE BUG THIS FIXES. A route is an intent until the gateway's CERTIFICATE
-- carries the prefix — nebula reads routing authority from the certificate and
-- nowhere else. Adding a route therefore leaves the machine holding a
-- certificate that does not authorise the routing it was just told to do, and
-- nothing asked it to get a new one. It picked one up on its ordinary renewal
-- schedule, roughly half a certificate lifetime away, so `orbit route add`
-- appeared to succeed and did nothing for days.
--
-- The mechanism to fix it already existed and was wired to one input. Enrolment
-- sets RenewAfter to now when a host's ADDRESS moved after its certificate was
-- issued, with the reasoning (internal/enroll/service.go) that a certificate
-- which no longer authorises the packets a host sends is downtime rather than
-- latency. A route is the same shape, so it gets the same treatment and the
-- same column shape as addr_changed_at.
--
-- NULLABLE, and null means "never changed" rather than "changed at the epoch".
-- Every membership that exists when this runs has whatever routes it has and a
-- certificate consistent with them; stamping them all would re-issue the entire
-- fleet's certificates on the next poll to correct nothing.
ALTER TABLE orbit.membership
    ADD COLUMN routes_changed_at timestamptz;
