package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// The control plane's own service files, generated by bootstrap.
//
// Bootstrap already knows the network id, the DSN, the CA key path, and the
// lighthouse address. Leaving an operator to assemble a unit file and an env
// file from those by hand is where a real deployment produced an empty
// ORBIT_NETWORK — systemd expands an unset variable to the empty string, so
// `-mesh ${ORBIT_NETWORK}=10.42.0.1` became `-mesh =10.42.0.1`, and the failure
// arrived as sixty lines of flag help.

// controlPlaneInstall describes the files bootstrap will write.
type controlPlaneInstall struct {
	EnvPath  string
	UnitPath string
	Env      string
	Unit     string
	Unit0644 bool
}

// planControlPlane renders the env file and the unit.
//
// Every value that made it into the unit came from bootstrap's own results, so
// there is nothing for an operator to copy across and nothing to mistype.
func planControlPlane(networkID, dsn, pepper, enrollURL, overlayAddr, lighthouse, caKey string) controlPlaneInstall {
	// The env file holds the secrets and the unit holds the flags. Splitting
	// them that way is what lets the unit be world-readable while the DSN and
	// the pepper are not, and it is why the unit refers to ${ORBIT_NETWORK}
	// rather than baking it in: one file is 0600 and the other is not.
	env := fmt.Sprintf(`# Generated by `+"`orbitd bootstrap`"+`. Mode 0600: it holds the database
# password and the enrollment pepper.
ORBIT_DSN=%s
ORBIT_ENROLL_PEPPER=%s
ORBIT_NETWORK=%s
`, dsn, pepper, networkID)

	var mesh string
	if overlayAddr != "" {
		mesh = fmt.Sprintf("    -mesh ${ORBIT_NETWORK}=%s \\\n", overlayAddr)
	}
	var lh string
	if lighthouse != "" {
		lh = fmt.Sprintf("    -lighthouse %s \\\n", lighthouse)
	}

	unit := fmt.Sprintf(`# Orbit control plane. Generated by `+"`orbitd bootstrap`"+`.
#
# Regenerating is the supported way to change it; hand edits are lost on the
# next bootstrap. ORBIT_NETWORK comes from the env file below — an unset one
# expands to the empty string here, which produces "-mesh =<addr>" and a flag
# parse error rather than anything that names the cause.

[Unit]
Description=Orbit control plane
After=network-online.target postgresql.service
Wants=network-online.target

[Service]
Type=exec
User=orbit
Group=orbit

EnvironmentFile=%s

ExecStart=%s serve \
    -addr 0.0.0.0:8080 \
    -metrics-addr 127.0.0.1:9464 \
    -ui-addr 127.0.0.1:8081 \
%s%s    -enroll-url %s

Restart=on-failure
RestartSec=5s

# The control plane holds a root of trust for the whole mesh. Give it as little
# of the machine as it can work with. It needs no tun device and no privileged
# port: it joins the overlay on a userspace network stack.
NoNewPrivileges=yes
PrivateTmp=yes
PrivateDevices=yes
ProtectSystem=strict
ProtectHome=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
RestrictNamespaces=yes
LockPersonality=yes
MemoryDenyWriteExecute=yes
SystemCallArchitectures=native
SystemCallFilter=@system-service
SystemCallFilter=~@privileged @resources

# Only the CA key's directory is writable.
ReadWritePaths=%s

[Install]
WantedBy=multi-user.target
`, controlPlaneEnvPath, orbitdPath(), lh, mesh, enrollURL, filepath.Dir(caKey))

	return controlPlaneInstall{
		EnvPath:  controlPlaneEnvPath,
		UnitPath: controlPlaneUnitPath,
		Env:      env,
		Unit:     unit,
	}
}

const (
	controlPlaneEnvPath  = "/etc/orbit/orbit.env"
	controlPlaneUnitPath = "/etc/systemd/system/orbit-control.service"
)

// orbitdPath is this binary, resolved. A unit naming a path the binary is not
// at starts once — from the shell that ran bootstrap — and never after a reboot.
func orbitdPath() string {
	p, err := os.Executable()
	if err != nil {
		return "/usr/local/bin/orbitd"
	}
	if resolved, err := filepath.EvalSymlinks(p); err == nil {
		return resolved
	}
	return p
}

// write puts both files in place.
//
// The env file is 0600 and the unit is 0644, which is the reason they are two
// files: the unit names paths and flags an operator should be able to read, and
// the env file holds a database password.
func (c controlPlaneInstall) write() error {
	if err := os.MkdirAll(filepath.Dir(c.EnvPath), 0o700); err != nil {
		return fmt.Errorf("create %s: %w", filepath.Dir(c.EnvPath), err)
	}
	if err := os.WriteFile(c.EnvPath, []byte(c.Env), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", c.EnvPath, err)
	}
	if err := os.MkdirAll(filepath.Dir(c.UnitPath), 0o755); err != nil {
		return fmt.Errorf("create %s: %w", filepath.Dir(c.UnitPath), err)
	}
	if err := os.WriteFile(c.UnitPath, []byte(c.Unit), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", c.UnitPath, err)
	}
	return nil
}

// describe is what bootstrap prints when it has written the files.
func (c controlPlaneInstall) describe() string {
	return strings.TrimSpace(fmt.Sprintf(`
wrote %s  (0600 — database password and enrollment pepper)
wrote %s  (0644)

Start it:

  systemctl daemon-reload && systemctl enable --now orbit-control
  curl -fsS localhost:8080/readyz`, c.EnvPath, c.UnitPath))
}
