package main

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strings"
)

// The control plane's own service files, generated by bootstrap.
//
// Bootstrap already knows the network id, the DSN, the CA key path, and the
// lighthouse address. Leaving an operator to assemble a unit file and an env
// file from those by hand is where a real deployment produced an empty
// ORBIT_NETWORK — systemd expands an unset variable to the empty string, so
// `-mesh ${ORBIT_NETWORK}=10.42.0.1` became `-mesh =10.42.0.1`, and the failure
// arrived as sixty lines of flag help.

// controlPlaneInstall describes the files bootstrap will write.
type controlPlaneInstall struct {
	EnvPath  string
	UnitPath string
	Env      string
	Unit     string

	// StateDir and CAKey are reported back so describe can name the two paths
	// the service account must own. Neither is chowned here: bootstrap runs as
	// root and the key it just wrote is still being used by this process.
	StateDir string
	CAKey    string
}

// planControlPlane renders the env file and the unit.
//
// Every value that made it into the unit came from bootstrap's own results, so
// there is nothing for an operator to copy across and nothing to mistype.
func planControlPlane(networkID, dsn, enrollURL, overlayAddr, lighthouse, caKey string) controlPlaneInstall {
	// The env file holds the secrets and the unit holds the flags. Splitting
	// them that way is what lets the unit be world-readable while the DSN is
	// not, and it is why the unit refers to ${ORBIT_NETWORK} rather than baking
	// it in: one file is 0600 and the other is not.
	env := fmt.Sprintf(`# Generated by `+"`orbitd bootstrap`"+`. Mode 0600: it holds the
# database password.
ORBIT_DSN=%s
ORBIT_NETWORK=%s
`, dsn, networkID)

	var mesh string
	if overlayAddr != "" {
		mesh = fmt.Sprintf("    -mesh ${ORBIT_NETWORK}=%s \\\n", overlayAddr)
	}
	var lh string
	if lighthouse != "" {
		lh = fmt.Sprintf("    -lighthouse %s \\\n", lighthouse)
	}

	unit := fmt.Sprintf(`# Orbit control plane. Generated by `+"`orbitd bootstrap`"+`.
#
# Regenerating is the supported way to change it; hand edits are lost on the
# next bootstrap. ORBIT_NETWORK comes from the env file below — an unset one
# expands to the empty string here, which produces "-mesh =<addr>" and a flag
# parse error rather than anything that names the cause.

[Unit]
Description=Orbit control plane
After=network-online.target postgresql.service
Wants=network-online.target

[Service]
Type=exec
User=%s
Group=%s

EnvironmentFile=%s

ExecStart=%s serve \
    -addr 0.0.0.0:8080 \
    -metrics-addr 127.0.0.1:9464 \
    -ui-addr 127.0.0.1:8081 \
%s%s    -enroll-url %s

Restart=on-failure
RestartSec=5s

# The control plane holds a root of trust for the whole mesh. Give it as little
# of the machine as it can work with. It needs no tun device and no privileged
# port: it joins the overlay on a userspace network stack.
NoNewPrivileges=yes
PrivateTmp=yes
PrivateDevices=yes
ProtectSystem=strict
ProtectHome=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
RestrictNamespaces=yes
LockPersonality=yes
MemoryDenyWriteExecute=yes
SystemCallArchitectures=native
SystemCallFilter=@system-service
SystemCallFilter=~@privileged @resources

# Only the CA key's directory is writable.
ReadWritePaths=%s

[Install]
WantedBy=multi-user.target
`, serviceUser, serviceUser, controlPlaneEnvPath, orbitdPath(), lh, mesh, enrollURL, filepath.Dir(caKey))

	return controlPlaneInstall{
		EnvPath:  controlPlaneEnvPath,
		UnitPath: controlPlaneUnitPath,
		Env:      env,
		Unit:     unit,
		StateDir: filepath.Dir(caKey),
		CAKey:    caKey,
	}
}

const (
	controlPlaneEnvPath  = "/etc/orbit/orbit.env"
	controlPlaneUnitPath = "/etc/systemd/system/orbit-control.service"
)

// orbitdPath is this binary, resolved. A unit naming a path the binary is not
// at starts once — from the shell that ran bootstrap — and never after a reboot.
func orbitdPath() string {
	p, err := os.Executable()
	if err != nil {
		return "/usr/local/bin/orbitd"
	}
	if resolved, err := filepath.EvalSymlinks(p); err == nil {
		return resolved
	}
	return p
}

// write puts both files in place.
//
// The env file is 0600 and the unit is 0644, which is the reason they are two
// files: the unit names paths and flags an operator should be able to read, and
// the env file holds a database password.
func (c controlPlaneInstall) write() error {
	// The account the unit runs as, before the unit that names it.
	//
	// Nothing else created it, and systemd refuses to start a unit whose User
	// does not exist — so `-write-unit` produced a unit that could never start,
	// and the failure arrived as "Failed to determine user credentials", which
	// names neither this flag nor the missing account.
	if err := ensureServiceUser(serviceUser); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(c.EnvPath), 0o700); err != nil {
		return fmt.Errorf("create %s: %w", filepath.Dir(c.EnvPath), err)
	}
	if err := os.WriteFile(c.EnvPath, []byte(c.Env), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", c.EnvPath, err)
	}
	if err := os.MkdirAll(filepath.Dir(c.UnitPath), 0o755); err != nil {
		return fmt.Errorf("create %s: %w", filepath.Dir(c.UnitPath), err)
	}
	if err := os.WriteFile(c.UnitPath, []byte(c.Unit), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", c.UnitPath, err)
	}
	return nil
}

// serviceUser is the unqualified account the control plane runs as. A system
// account with no login shell and no home: it needs to read two files and write
// one directory.
const serviceUser = "orbit"

// ensureServiceUser creates the account if it is missing.
//
// Idempotent, and tolerant of the several ways a distribution can spell this:
// useradd on RHEL and Debian families, adduser on Alpine. A host that already
// has the account — because bootstrap ran before, or because a package made it
// — is left alone.
func ensureServiceUser(name string) error {
	if _, err := user.Lookup(name); err == nil {
		return nil
	}

	// -r system account, -s nologin, -M no home. The CA key's directory is
	// created and chowned separately, so this account owns nothing at creation.
	cmds := [][]string{
		{"useradd", "--system", "--no-create-home", "--shell", "/sbin/nologin", name},
		{"adduser", "-S", "-D", "-H", "-s", "/sbin/nologin", name},
	}
	var last error
	for _, argv := range cmds {
		path, err := exec.LookPath(argv[0])
		if err != nil {
			continue
		}
		if out, err := exec.Command(path, argv[1:]...).CombinedOutput(); err != nil {
			last = fmt.Errorf("%s: %w: %s", argv[0], err, strings.TrimSpace(string(out)))
			continue
		}
		return nil
	}
	if last == nil {
		last = errors.New("no useradd or adduser on this host")
	}
	return fmt.Errorf("create the %q service account (the unit runs as it): %w", name, last)
}

// describe is what bootstrap prints when it has written the files.
func (c controlPlaneInstall) describe() string {
	return strings.TrimSpace(fmt.Sprintf(`
created user %s  (system account the unit runs as)
wrote %s  (0600 — database password)
wrote %s  (0644)

Give the service account its state directory and the CA key:

  install -d -o %s -g %s -m 0750 %s
  chown %s:%s %s && chmod 0600 %s

Then start it:

  systemctl daemon-reload && systemctl enable --now orbit-control
  curl -fsS localhost:8080/readyz`,
		serviceUser, c.EnvPath, c.UnitPath,
		serviceUser, serviceUser, c.StateDir,
		serviceUser, serviceUser, c.CAKey, c.CAKey))
}
