// Package secrets stores Orbit's private keys in Postgres, encrypted under a
// key that is not in Postgres.
//
// WHY THIS EXISTS.
//
// Every private key the control plane holds — a network's CA signing key, a
// network's identity key — used to be a file on one machine, named by a
// `file://` signer ref. That is defensible for a single VM and does not survive
// a second one: adding a replica meant copying N files per network by hand,
// keeping them in step through every CA rotation, with nothing to detect drift.
// A replica holding a stale CA key does not fail at startup; it fails when
// somebody is trying to add a machine.
//
// THE PROPERTY THIS MUST NOT BREAK.
//
//	Read access to the database does not let an attacker mint a certificate.
//
// That is what makes a leaked pg_dump, an SQL-injection bug, or a compromised
// read replica survivable rather than fatal. Envelope encryption preserves it
// exactly: the database holds ciphertext, and the key encryption key (KEK) lives
// where the CA key used to — on the control-plane host, in an environment
// variable or a TPM-sealed credential.
//
// Before: an attacker needed (database read) + (file read on the host).
// After:  an attacker needs (database read) + (the KEK, on the host).
//
// Same two factors, same hosts, no regression — and one secret per deployment
// instead of N files per network. See docs/key-custody.md.
//
// WHAT THIS IS NOT. It is not a general secret store, and nothing outside this
// package should put anything in it. Enrollment codes are hashed, not encrypted;
// API tokens are hashed; device and mesh private keys never reach the control
// plane at all and migrations 0011, 0013 and 0017 carry tripwires that fail if a
// column which could hold one is added.
package secrets

import (
	"bytes"
	"crypto/rand"
	"errors"
	"fmt"
	"os"
	"strconv"

	"golang.org/x/crypto/argon2"
	"golang.org/x/crypto/chacha20poly1305"
)

// Kind labels what a stored secret is for.
//
// Not decoration: it is bound into the AEAD's additional data, so a row cannot
// be reinterpreted as a different kind of key. An attacker with database WRITE
// could otherwise move a network identity key into a CA's row — both are
// Ed25519 — and have the control plane sign certificates with a key whose
// custody rules are weaker.
type Kind string

const (
	KindCASigning       Kind = "ca_signing_key"
	KindNetworkIdentity Kind = "network_identity_key"
)

var (
	// ErrNoKEK means no passphrase was configured. Distinct because the fix is
	// an operator action with an obvious shape, and because a control plane
	// that started without one would fail later, at signing time.
	ErrNoKEK = errors.New("no key encryption key: set ORBIT_KEK_PASSPHRASE or ORBIT_KEK_PASSPHRASE_FILE")

	// ErrWrongKEK means the passphrase does not match the one this deployment
	// was initialised with.
	//
	// Detected at STARTUP by a verifier, not on the first decrypt. A replica
	// with the wrong passphrase that started cleanly and failed at its first
	// signing operation would fail while somebody was adding a machine, which
	// is the worst moment and the hardest to attribute.
	ErrWrongKEK = errors.New("the key encryption key does not match this deployment")

	// ErrNotFound means the ref names no stored secret.
	ErrNotFound = errors.New("no such stored secret")
)

// Argon2id parameters.
//
// 64 MiB, three passes, four lanes. NOT nebula-cert's 2 GiB, and the difference
// is deliberate.
//
// nebula-cert derives once, interactively, on a workstation. This derives at
// every control-plane START, on a VM sized at 2 vCPU / 2 GB with Postgres
// sharing it. A 2 GiB allocation there is most of the machine, at the moment the
// process is least able to spare it — and an OOM kill at boot turns a
// deployment's key custody into a deployment that does not start.
//
// (An earlier version of this comment justified the choice by claiming orbitd
// already peaks near 2 GB. That was repeated from a docs figure taken during a
// crash loop and is wrong by two orders of magnitude — measured, the whole
// process peaks at ~108 MB with two nebula stacks running. The conclusion holds
// on the plainer argument above; the false premise did not deserve to survive in
// a comment justifying a security parameter.)
//
// 64 MiB is comfortably above OWASP's Argon2id floor and costs about a tenth of
// a second. It is also more headroom than the threat needs: the passphrase is
// machine-generated by the setup script, like the database password, and against
// a high-entropy secret the KDF's cost is nearly irrelevant — the same argument
// that retired the enrollment pepper. The cost is here for the operator who
// types a passphrase they chose themselves, which is the case worth defending.
//
// ORBIT_KEK_ARGON_MEMORY_MIB raises it for a deployment with memory to spare.
// Lowering it below the default is refused: a knob that can weaken a KDF is one
// somebody eventually turns the wrong way while chasing a slow boot.
const (
	defaultArgonMemory  = 64 * 1024 // KiB
	defaultArgonTime    = 3
	defaultArgonThreads = 4

	kekLen  = chacha20poly1305.KeySize
	saltLen = 16
)

// The parameters actually used, as variables so tests can turn them down.
//
// A package-level knob rather than a parameter on DeriveKEK: production has one
// right answer, and threading it through every call site would invite a caller
// to pick a weaker one.
var (
	argonMemory  uint32 = defaultArgonMemory
	argonTime    uint32 = defaultArgonTime
	argonThreads uint8  = defaultArgonThreads
)

// ConfigureKDF raises the derivation cost from the environment.
//
// One direction only. A deployment with memory to spare can ask for more;
// nothing can ask for less, because the failure mode of a too-cheap KDF is
// silent and the failure mode of a too-expensive one is a boot that is visibly
// slow.
//
// Changing this AFTER bootstrap makes existing secrets unopenable — the salt is
// stored, the parameters are not — so the error says so rather than leaving an
// operator to discover it as a wrong-passphrase report.
func ConfigureKDF() error {
	v := os.Getenv("ORBIT_KEK_ARGON_MEMORY_MIB")
	if v == "" {
		return nil
	}
	mib, err := strconv.Atoi(v)
	if err != nil {
		return fmt.Errorf("ORBIT_KEK_ARGON_MEMORY_MIB is not a number: %w", err)
	}
	if kib := uint32(mib) * 1024; mib > 0 && kib >= defaultArgonMemory {
		argonMemory = kib
		return nil
	}
	return fmt.Errorf("ORBIT_KEK_ARGON_MEMORY_MIB is %d, which is below the built-in %d MiB; "+
		"it can only be raised", mib, defaultArgonMemory/1024)
}

// verifierPlaintext is what a deployment encrypts once so a later start can tell
// a wrong passphrase from a corrupt row.
const verifierPlaintext = "orbit-kek-verifier-v1"

// KEK is a derived key encryption key.
//
// Held in memory for the process's lifetime. There is no attempt to lock it out
// of swap or scrub it: a process that can read its own memory can read the keys
// it has already decrypted, so protecting the KEK specifically would be theatre
// while the plaintext CA key sits in the same heap.
type KEK struct {
	key []byte
}

// DeriveKEK turns a passphrase and a per-deployment salt into a KEK.
//
// The salt is stored in the database and is not secret — its job is to make the
// derivation specific to this deployment, so the same passphrase used twice
// yields two unrelated keys.
func DeriveKEK(passphrase, salt []byte) (*KEK, error) {
	if len(passphrase) == 0 {
		return nil, ErrNoKEK
	}
	if len(salt) != saltLen {
		return nil, fmt.Errorf("kek salt must be %d bytes, got %d", saltLen, len(salt))
	}
	key := argon2.IDKey(passphrase, salt, argonTime, argonMemory, argonThreads, kekLen)
	return &KEK{key: key}, nil
}

// NewSalt generates a per-deployment salt.
func NewSalt() ([]byte, error) {
	salt := make([]byte, saltLen)
	if _, err := rand.Read(salt); err != nil {
		return nil, fmt.Errorf("generate kek salt: %w", err)
	}
	return salt, nil
}

// Seal encrypts a secret.
//
// XChaCha20-Poly1305 with a random 24-byte nonce. Extended-nonce specifically:
// at 192 bits a random nonce cannot realistically repeat, so there is no counter
// to keep and no way for two replicas to collide by both encrypting at once.
// AES-GCM's 96-bit nonce would have made that a thing to reason about.
//
// The additional data binds the ciphertext to its id and kind, so a row moved or
// relabelled in the database fails to open rather than decrypting into the wrong
// role. That is the difference between an attacker with database write causing
// an outage and causing a key substitution.
func (k *KEK) Seal(id string, kind Kind, plaintext []byte) (nonce, ciphertext []byte, err error) {
	aead, err := chacha20poly1305.NewX(k.key)
	if err != nil {
		return nil, nil, err
	}
	nonce = make([]byte, aead.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		return nil, nil, fmt.Errorf("generate nonce: %w", err)
	}
	return nonce, aead.Seal(nil, nonce, plaintext, aad(id, kind)), nil
}

// Open decrypts a secret.
func (k *KEK) Open(id string, kind Kind, nonce, ciphertext []byte) ([]byte, error) {
	aead, err := chacha20poly1305.NewX(k.key)
	if err != nil {
		return nil, err
	}
	if len(nonce) != aead.NonceSize() {
		return nil, fmt.Errorf("stored nonce is %d bytes, want %d", len(nonce), aead.NonceSize())
	}
	out, err := aead.Open(nil, nonce, ciphertext, aad(id, kind))
	if err != nil {
		// Deliberately not distinguishing "wrong key" from "tampered" — the
		// AEAD cannot tell them apart, and pretending otherwise in the message
		// would send an operator down the wrong path. ErrWrongKEK is reported
		// by the startup verifier, which CAN tell.
		return nil, fmt.Errorf("could not decrypt %s %s: wrong key encryption key, or the row was altered", kind, id)
	}
	return out, nil
}

// aad binds a ciphertext to the row it lives in.
func aad(id string, kind Kind) []byte {
	return []byte(string(kind) + "\x00" + id)
}

// SealVerifier produces the value a later start checks the passphrase against.
func (k *KEK) SealVerifier() (nonce, ciphertext []byte, err error) {
	return k.Seal("verifier", "verifier", []byte(verifierPlaintext))
}

// CheckVerifier reports whether this KEK is the one the deployment was
// initialised with.
func (k *KEK) CheckVerifier(nonce, ciphertext []byte) error {
	got, err := k.Open("verifier", "verifier", nonce, ciphertext)
	if err != nil || string(got) != verifierPlaintext {
		return ErrWrongKEK
	}
	return nil
}

//------------------------------------------------------------------------------
// Passphrase
//------------------------------------------------------------------------------

// Passphrase reads the KEK passphrase from the environment.
//
// From a file if ORBIT_KEK_PASSPHRASE_FILE is set, otherwise from
// ORBIT_KEK_PASSPHRASE. The file form exists because it is what
// `systemd-creds --with-key=host+tpm2` produces: the passphrase is sealed to the
// machine's TPM and appears as a file the unit can read, never as an environment
// variable that `ps`, a crash dump, or `docker inspect` would carry.
//
// FALLS BACK TO THE CA KEY PASSPHRASE. A deployment that already set
// ORBIT_CA_KEY_PASSPHRASE for its on-disk CA key should not have to set a second
// secret to keep working — the two protect the same material for the same
// reason, and demanding a new variable at upgrade time is how an upgrade turns
// into an outage. New deployments should set the KEK one.
func Passphrase() ([]byte, error) {
	for _, v := range []struct{ file, direct string }{
		{"ORBIT_KEK_PASSPHRASE_FILE", "ORBIT_KEK_PASSPHRASE"},
		{"ORBIT_CA_KEY_PASSPHRASE_FILE", "ORBIT_CA_KEY_PASSPHRASE"},
	} {
		if path := os.Getenv(v.file); path != "" {
			b, err := os.ReadFile(path)
			if err != nil {
				return nil, fmt.Errorf("read %s: %w", v.file, err)
			}
			// Trailing newline trimmed: every way of producing this file adds
			// one, and a passphrase that works from `echo -n` and fails from
			// `echo` is a bug report nobody enjoys.
			return bytes.TrimRight(b, "\r\n"), nil
		}
		if s := os.Getenv(v.direct); s != "" {
			return []byte(s), nil
		}
	}
	return nil, ErrNoKEK
}
